name 'cesnet-sentry'
version '0.1.0'
source 'https://github.com/MetaCenterCloudPuppet/cesnet-sentry'
author 'Frantisek Dvorak <valtri@civ.zcu.cz>'
license 'MIT'
summary 'Apache Sentry Setup'
description 'Apache Sentry Setup'
project_page 'https://github.com/MetaCenterCloudPuppet/cesnet-sentry'

dependency 'puppetlabs/stdlib', '>= 1.0.0 < 5.0.0'
